### ISSUE TITLE
'build.sh' fails with `PermissionError` when run as root

### ISSUE THREAD

**Issue by allanlewis** [phracek/pycharm-community-edition#23]
I want to be able to run `build.sh` as root to avoid the password prompt from `mock`. However, currently I get an error:
```
$ sudo ./build.sh 
<snip>
Building SRPM...
Building RPMs using mock...
INFO: mock.py version 1.2.18 starting (python version = 3.4.3)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(/home/alewis/git/pycharm-community-edition/results/pycharm-community-2016.2-1.fc23.src.rpm)  Config(fedora-23-x86_64)
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
Start: unpacking root cache
Finish: unpacking root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
ERROR: Exception(/home/alewis/git/pycharm-community-edition/results/pycharm-community-2016.2-1.fc23.src.rpm) Config(fedora-23-x86_64) 0 minutes 2 seconds
INFO: Results and/or logs in: /home/alewis/git/pycharm-community-edition/results
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
Traceback (most recent call last):
  File "/sbin/mock", line 849, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/sbin/mock", line 664, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/sbin/mock", line 747, in run_command
    do_rebuild(config_opts, commands, buildroot, args)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/sbin/mock", line 505, in do_rebuild
    post=post_build, clean=clean)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/sbin/mock", line 448, in rebuild_generic
    commands.init(prebuild=not config_opts.get('short_circuit'))
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/backend.py", line 124, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/buildroot.py", line 90, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/buildroot.py", line 130, in _init
    self._resetLogging()
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/buildroot.py", line 308, in _resetLogging
    fh = logging.FileHandler(fullPath, "a+")
  File "/usr/lib64/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/alewis/git/pycharm-community-edition/results/state.log'
```
This happens on a clean repo in Fedora 23.

**Comment by allanlewis** [comment]
I think I've found a fix for this; WIP allanlewis/pycharm-community-edition@fix-sudo-build.
